using BudgetPlanner_UI.Interfaces;
using BudgetPlanner_UI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace BudgetPlanner_UI.Views
{
    /// <summary>
    /// Interaction logic for BudgetView.xaml
    /// </summary>
    public partial class BudgetView : UserControl, IView
    {
        public BudgetView( BudgetViewModel vm)
        {
            InitializeComponent();
            DataContext = vm;
            SetBindings();
        }

        public void SetBindings( )
        {
            var vm = DataContext as BudgetViewModel;
            //IncomeDataGrid.CellEditEnding += vm.CellEditEvent;
            IncomeDataGrid.CurrentCellChanged += vm.IncomeCellChangedEvent;
            IncomeDataGrid.AutoGeneratedColumns += vm.IncomeCellChangedEvent;
            ExpenseDataGrid.CurrentCellChanged += vm.ExpenseCellChangedEvent;
            ExpenseDataGrid.AutoGeneratedColumns += vm.ExpenseCellChangedEvent;
            IncomeDataGrid.KeyUp += vm.KeyUpEvent;
            ExpenseDataGrid.KeyUp += vm.KeyUpEvent;
        }

    }
}
